### ISSUE TITLE
Client-only mod EffectsLeft in server package crashes loading

### ISSUE THREAD

**Issue by CarlSmotricz** [vizthex123/viz-projects-old#5]
There's a client-only mod "EffectsLeft" in TEoE Server Pack v4.0 from July 18.
It crashes loading on the server.

Server loaded fine once I removed that mod's jar from the mod directory.

**Comment by vizthex123** [comment]
I thought I'd removed it?

Will check on it.

**Comment by vizthex123** [comment]
Alright, I've uploaded a fixed version.
