### ISSUE TITLE
충돌하는이유?

### ISSUE THREAD

**Issue by Murdersands** [vizthex123/viz-projects-old#6]
**Modpack Version:** 1.19

**What caused the crash?** 

**Steps to reproduce, if applicable:**

***Be sure to attach the game log!***

*To do so, navigate to the `logs` folder inside of the modpack's folder. Right-click on the pack then `open folder` to get there, or navigate to the CurseForge install location.*

**Comment by vizthex123** [comment]
Please change the title to English and attach the `latest.log` (instructions on how to get it are in the template).

If this is about the Project Table crashing the game, I've [reported it to the dev](https://github.com/Qmunity/BluePower/issues/624) so hopefully it gets fixed soon.

**Comment by vizthex123** [comment]
I don't know what this issue is about, so I'm closing it.
